"""Initial schema — all 7 tables

Revision ID: 59fa41c9a6f4
Revises: 
Create Date: 2026-03-30 19:37:22.602244

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '59fa41c9a6f4'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('account_snapshots',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('balance', sa.Float(), nullable=False),
    sa.Column('eod_threshold', sa.Float(), nullable=False),
    sa.Column('daily_pnl', sa.Float(), nullable=False),
    sa.Column('phase', sa.String(length=8), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_account_snapshots_timestamp'), 'account_snapshots', ['timestamp'], unique=False)
    op.create_table('circuit_breaker_events',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('trigger_type', sa.String(length=32), nullable=False),
    sa.Column('trigger_value', sa.Text(), nullable=True),
    sa.Column('positions_flattened', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_circuit_breaker_events_timestamp'), 'circuit_breaker_events', ['timestamp'], unique=False)
    op.create_table('config_history',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('parameter_name', sa.String(length=128), nullable=False),
    sa.Column('old_value', sa.Text(), nullable=True),
    sa.Column('new_value', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_config_history_timestamp'), 'config_history', ['timestamp'], unique=False)
    op.create_table('events',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('impact_level', sa.String(length=8), nullable=False),
    sa.Column('actual', sa.Text(), nullable=True),
    sa.Column('forecast', sa.Text(), nullable=True),
    sa.Column('previous', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_events_timestamp'), 'events', ['timestamp'], unique=False)
    op.create_table('signals',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('instrument', sa.String(length=16), nullable=False),
    sa.Column('strategy_name', sa.String(length=64), nullable=False),
    sa.Column('direction', sa.String(length=8), nullable=False),
    sa.Column('entry_price', sa.Float(), nullable=False),
    sa.Column('sl_price', sa.Float(), nullable=False),
    sa.Column('tp_price', sa.Float(), nullable=False),
    sa.Column('rr_ratio', sa.Float(), nullable=False),
    sa.Column('confidence_score', sa.Float(), nullable=False),
    sa.Column('confluence_factors', sa.JSON(), nullable=True),
    sa.Column('indicator_state', sa.JSON(), nullable=True),
    sa.Column('decision', sa.String(length=16), nullable=True),
    sa.Column('decision_timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_signals_instrument'), 'signals', ['instrument'], unique=False)
    op.create_index(op.f('ix_signals_timestamp'), 'signals', ['timestamp'], unique=False)
    op.create_table('phantom_trades',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('signal_id', sa.String(length=32), nullable=False),
    sa.Column('would_have_hit_tp', sa.Boolean(), nullable=True),
    sa.Column('would_have_hit_sl', sa.Boolean(), nullable=True),
    sa.Column('phantom_pnl', sa.Float(), nullable=True),
    sa.Column('phantom_duration', sa.Float(), nullable=True),
    sa.Column('max_favorable_excursion', sa.Float(), nullable=True),
    sa.Column('max_adverse_excursion', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['signal_id'], ['signals.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_phantom_trades_signal_id'), 'phantom_trades', ['signal_id'], unique=False)
    op.create_table('trades',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('signal_id', sa.String(length=32), nullable=False),
    sa.Column('order_id', sa.String(length=64), nullable=False),
    sa.Column('fill_price', sa.Float(), nullable=True),
    sa.Column('fill_timestamp', sa.DateTime(), nullable=True),
    sa.Column('exit_price', sa.Float(), nullable=True),
    sa.Column('exit_timestamp', sa.DateTime(), nullable=True),
    sa.Column('actual_pnl', sa.Float(), nullable=True),
    sa.Column('slippage', sa.Float(), nullable=True),
    sa.Column('duration_seconds', sa.Float(), nullable=True),
    sa.Column('was_override', sa.Boolean(), nullable=False),
    sa.Column('override_details', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['signal_id'], ['signals.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trades_signal_id'), 'trades', ['signal_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_trades_signal_id'), table_name='trades')
    op.drop_table('trades')
    op.drop_index(op.f('ix_phantom_trades_signal_id'), table_name='phantom_trades')
    op.drop_table('phantom_trades')
    op.drop_index(op.f('ix_signals_timestamp'), table_name='signals')
    op.drop_index(op.f('ix_signals_instrument'), table_name='signals')
    op.drop_table('signals')
    op.drop_index(op.f('ix_events_timestamp'), table_name='events')
    op.drop_table('events')
    op.drop_index(op.f('ix_config_history_timestamp'), table_name='config_history')
    op.drop_table('config_history')
    op.drop_index(op.f('ix_circuit_breaker_events_timestamp'), table_name='circuit_breaker_events')
    op.drop_table('circuit_breaker_events')
    op.drop_index(op.f('ix_account_snapshots_timestamp'), table_name='account_snapshots')
    op.drop_table('account_snapshots')
    # ### end Alembic commands ###
