"""
SQLAlchemy ORM models for all database tables.

Designed for SQLite (v1) with a clear migration path to PostgreSQL.
All enums stored as TEXT for readability and portability.
All timestamps stored in UTC.
"""

from __future__ import annotations

import uuid
from datetime import datetime

from sqlalchemy import Boolean, DateTime, Float, Integer, String, Text
from sqlalchemy import JSON
from sqlalchemy import ForeignKey
from sqlalchemy.orm import DeclarativeBase, Mapped, mapped_column, relationship


def _uuid() -> str:
    return uuid.uuid4().hex


def _utcnow() -> datetime:
    return datetime.utcnow()


class Base(DeclarativeBase):
    pass


# ---------------------------------------------------------------------------
# signals — every signal generated by a strategy
# ---------------------------------------------------------------------------


class SignalRecord(Base):
    __tablename__ = "signals"

    id: Mapped[str] = mapped_column(String(32), primary_key=True)
    timestamp: Mapped[datetime] = mapped_column(DateTime, default=_utcnow, index=True)
    instrument: Mapped[str] = mapped_column(String(16), index=True)
    strategy_name: Mapped[str] = mapped_column(String(64))
    direction: Mapped[str] = mapped_column(String(8))  # LONG | SHORT
    entry_price: Mapped[float] = mapped_column(Float)
    sl_price: Mapped[float] = mapped_column(Float)
    tp_price: Mapped[float] = mapped_column(Float)
    rr_ratio: Mapped[float] = mapped_column(Float)
    confidence_score: Mapped[float] = mapped_column(Float)
    confluence_factors: Mapped[dict | None] = mapped_column(JSON, nullable=True)
    indicator_state: Mapped[dict | None] = mapped_column(JSON, nullable=True)
    decision: Mapped[str | None] = mapped_column(
        String(16), nullable=True
    )  # ACCEPTED | REJECTED | EXPIRED
    decision_timestamp: Mapped[datetime | None] = mapped_column(
        DateTime, nullable=True
    )

    # Relationships
    trade: Mapped[TradeRecord | None] = relationship(
        "TradeRecord", back_populates="signal", uselist=False
    )
    phantom_trade: Mapped[PhantomTradeRecord | None] = relationship(
        "PhantomTradeRecord", back_populates="signal", uselist=False
    )


# ---------------------------------------------------------------------------
# trades — every executed trade (accepted signals that were placed)
# ---------------------------------------------------------------------------


class TradeRecord(Base):
    __tablename__ = "trades"

    id: Mapped[str] = mapped_column(String(32), primary_key=True, default=_uuid)
    signal_id: Mapped[str] = mapped_column(
        String(32), ForeignKey("signals.id"), index=True
    )
    order_id: Mapped[str] = mapped_column(String(64))
    fill_price: Mapped[float | None] = mapped_column(Float, nullable=True)
    fill_timestamp: Mapped[datetime | None] = mapped_column(DateTime, nullable=True)
    exit_price: Mapped[float | None] = mapped_column(Float, nullable=True)
    exit_timestamp: Mapped[datetime | None] = mapped_column(DateTime, nullable=True)
    actual_pnl: Mapped[float | None] = mapped_column(Float, nullable=True)
    slippage: Mapped[float | None] = mapped_column(Float, nullable=True)
    duration_seconds: Mapped[float | None] = mapped_column(Float, nullable=True)
    was_override: Mapped[bool] = mapped_column(Boolean, default=False)
    override_details: Mapped[dict | None] = mapped_column(JSON, nullable=True)

    # Relationship
    signal: Mapped[SignalRecord] = relationship(
        "SignalRecord", back_populates="trade"
    )


# ---------------------------------------------------------------------------
# phantom_trades — track what would have happened on rejected/expired signals
# ---------------------------------------------------------------------------


class PhantomTradeRecord(Base):
    __tablename__ = "phantom_trades"

    id: Mapped[str] = mapped_column(String(32), primary_key=True, default=_uuid)
    signal_id: Mapped[str] = mapped_column(
        String(32), ForeignKey("signals.id"), index=True
    )
    would_have_hit_tp: Mapped[bool | None] = mapped_column(Boolean, nullable=True)
    would_have_hit_sl: Mapped[bool | None] = mapped_column(Boolean, nullable=True)
    phantom_pnl: Mapped[float | None] = mapped_column(Float, nullable=True)
    phantom_duration: Mapped[float | None] = mapped_column(
        Float, nullable=True
    )  # seconds
    max_favorable_excursion: Mapped[float | None] = mapped_column(
        Float, nullable=True
    )
    max_adverse_excursion: Mapped[float | None] = mapped_column(
        Float, nullable=True
    )

    # Relationship
    signal: Mapped[SignalRecord] = relationship(
        "SignalRecord", back_populates="phantom_trade"
    )


# ---------------------------------------------------------------------------
# account_snapshots — periodic snapshots of account state
# ---------------------------------------------------------------------------


class AccountSnapshotRecord(Base):
    __tablename__ = "account_snapshots"

    id: Mapped[str] = mapped_column(String(32), primary_key=True, default=_uuid)
    timestamp: Mapped[datetime] = mapped_column(DateTime, default=_utcnow, index=True)
    balance: Mapped[float] = mapped_column(Float)
    eod_threshold: Mapped[float] = mapped_column(Float)
    daily_pnl: Mapped[float] = mapped_column(Float)
    phase: Mapped[str] = mapped_column(String(8))  # EVAL | PA


# ---------------------------------------------------------------------------
# events — economic calendar events
# ---------------------------------------------------------------------------


class EventRecord(Base):
    __tablename__ = "events"

    id: Mapped[str] = mapped_column(String(32), primary_key=True, default=_uuid)
    timestamp: Mapped[datetime] = mapped_column(DateTime, index=True)
    name: Mapped[str] = mapped_column(String(256))
    impact_level: Mapped[str] = mapped_column(String(8))  # HIGH | MEDIUM | LOW
    actual: Mapped[str | None] = mapped_column(Text, nullable=True)
    forecast: Mapped[str | None] = mapped_column(Text, nullable=True)
    previous: Mapped[str | None] = mapped_column(Text, nullable=True)


# ---------------------------------------------------------------------------
# circuit_breaker_events — when auto or manual kill switch triggered
# ---------------------------------------------------------------------------


class CircuitBreakerEventRecord(Base):
    __tablename__ = "circuit_breaker_events"

    id: Mapped[str] = mapped_column(String(32), primary_key=True, default=_uuid)
    timestamp: Mapped[datetime] = mapped_column(DateTime, default=_utcnow, index=True)
    trigger_type: Mapped[str] = mapped_column(
        String(32)
    )  # MANUAL | MAX_CONSECUTIVE_LOSSES | ...
    trigger_value: Mapped[str | None] = mapped_column(Text, nullable=True)
    positions_flattened: Mapped[int] = mapped_column(Integer, default=0)


# ---------------------------------------------------------------------------
# config_history — track configuration changes over time
# ---------------------------------------------------------------------------


class ConfigHistoryRecord(Base):
    __tablename__ = "config_history"

    id: Mapped[str] = mapped_column(String(32), primary_key=True, default=_uuid)
    timestamp: Mapped[datetime] = mapped_column(DateTime, default=_utcnow, index=True)
    parameter_name: Mapped[str] = mapped_column(String(128))
    old_value: Mapped[str | None] = mapped_column(Text, nullable=True)
    new_value: Mapped[str | None] = mapped_column(Text, nullable=True)
